=== floration/mod-creator/examples/azuregrove/.modcreator/schema/advancement.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "kind": {
      "type": "string",
      "const": "advancement"
    },
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9_]+$"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "advancement": {
      "type": "object",
      "properties": {
        "parent": {
          "type": "string",
          "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
        },
        "description": {
          "default": "",
          "type": "string"
        },
        "icon": {
          "type": "string",
          "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
        },
        "frame": {
          "default": "task",
          "type": "string",
          "enum": [
            "task",
            "goal",
            "challenge"
          ]
        },
        "background": {
          "type": "string"
        },
        "criteria": {
          "minItems": 1,
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "obtain"
                  },
                  "item": {
                    "type": "string",
                    "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
                  },
                  "count": {
                    "default": 1,
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 6400
                  }
                },
                "required": [
                  "type",
                  "item"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "kill"
                  },
                  "mob": {
                    "type": "string",
                    "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
                  }
                },
                "required": [
                  "type",
                  "mob"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "visit"
                  },
                  "biome": {
                    "type": "string",
                    "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
                  }
                },
                "required": [
                  "type",
                  "biome"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "craft"
                  },
                  "recipe": {
                    "type": "string",
                    "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
                  }
                },
                "required": [
                  "type",
                  "recipe"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "eat"
                  },
                  "item": {
                    "type": "string",
                    "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
                  }
                },
                "required": [
                  "type",
                  "item"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "place"
                  },
                  "block": {
                    "type": "string",
                    "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
                  }
                },
                "required": [
                  "type",
                  "block"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "breed"
                  },
                  "mob": {
                    "type": "string",
                    "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
                  }
                },
                "required": [
                  "type",
                  "mob"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "tame"
                  },
                  "mob": {
                    "type": "string",
                    "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
                  }
                },
                "required": [
                  "type",
                  "mob"
                ]
              }
            ]
          }
        },
        "requires": {
          "default": "all",
          "type": "string",
          "enum": [
            "all",
            "any"
          ]
        },
        "announce": {
          "default": true,
          "type": "boolean"
        },
        "hidden": {
          "default": false,
          "type": "boolean"
        },
        "rewards": {
          "default": {
            "experience": 0,
            "items": [],
            "recipes": []
          },
          "type": "object",
          "properties": {
            "experience": {
              "default": 0,
              "type": "integer",
              "minimum": 0,
              "maximum": 100000
            },
            "items": {
              "default": [],
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "item": {
                    "type": "string",
                    "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
                  },
                  "count": {
                    "default": 1,
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 99
                  }
                },
                "required": [
                  "item"
                ]
              }
            },
            "recipes": {
              "default": [],
              "type": "array",
              "items": {
                "type": "string",
                "pattern": "^(#?[a-z0-9_.-]+:)?[a-z0-9_/.-]+$"
              }
            }
          }
        }
      },
      "required": [
        "icon",
        "criteria"
      ]
    }
  },
  "required": [
    "kind",
    "id",
    "name",
    "advancement"
  ]
}

=== floration/mod-creator/examples/azuregrove/spec/advancements/plum_picker.json
{
  "$schema": "../../.modcreator/schema/advancement.json",
  "kind": "advancement",
  "id": "plum_picker",
  "name": "Plum Picker",
  "advancement": {
    "parent": "azure_grove",
    "description": "Eat an Azure Plum",
    "icon": "azure_plum",
    "criteria": [
      {
        "type": "eat",
        "item": "azure_plum"
      }
    ],
    "rewards": {
      "recipes": [
        "azurewood_door"
      ]
    }
  }
}

=== floration/mod-creator/examples/azuregrove/spec/advancements/blue_rocks.json
{
  "$schema": "../../.modcreator/schema/advancement.json",
  "kind": "advancement",
  "id": "blue_rocks",
  "name": "Blue Rocks",
  "advancement": {
    "parent": "azure_grove",
    "description": "Mine some azurite",
    "icon": "azurite",
    "criteria": [
      {
        "type": "obtain",
        "item": "azurite"
      }
    ]
  }
}

=== floration/mod-creator/examples/azuregrove/spec/advancements/sharp_and_blue.json
{
  "$schema": "../../.modcreator/schema/advancement.json",
  "kind": "advancement",
  "id": "sharp_and_blue",
  "name": "Sharp and Blue",
  "advancement": {
    "parent": "blue_rocks",
    "description": "Craft an Azurite Sword",
    "icon": "azurite_sword",
    "frame": "goal",
    "criteria": [
      {
        "type": "craft",
        "recipe": "azurite_sword"
      }
    ],
    "rewards": {
      "experience": 20
    }
  }
}

=== floration/mod-creator/examples/azuregrove/spec/advancements/tusk_rancher.json
{
  "$schema": "../../.modcreator/schema/advancement.json",
  "kind": "advancement",
  "id": "tusk_rancher",
  "name": "Tusk Rancher",
  "advancement": {
    "parent": "plum_picker",
    "description": "Breed two Bluetusks with plums",
    "icon": "bluetusk_spawn_egg",
    "criteria": [
      {
        "type": "breed",
        "mob": "bluetusk"
      }
    ]
  }
}

=== floration/mod-creator/examples/azuregrove/spec/advancements/azure_grove.json
{
  "$schema": "../../.modcreator/schema/advancement.json",
  "kind": "advancement",
  "id": "azure_grove",
  "name": "Azure Grove",
  "advancement": {
    "description": "Find an Azure Grove",
    "icon": "azurewood_sapling",
    "background": "art/azurewood_planks.png",
    "criteria": [
      {
        "type": "visit",
        "biome": "azure_grove"
      }
    ]
  }
}

=== floration/mod-creator/examples/azuregrove/spec/advancements/brick_by_brick.json
{
  "$schema": "../../.modcreator/schema/advancement.json",
  "kind": "advancement",
  "id": "brick_by_brick",
  "name": "Brick by Brick",
  "advancement": {
    "parent": "blue_rocks",
    "description": "Place azurite brick stairs or a wall",
    "icon": "azurite_brick_stairs",
    "criteria": [
      {
        "type": "place",
        "block": "azurite_brick_stairs"
      },
      {
        "type": "place",
        "block": "azurite_brick_wall"
      }
    ],
    "requires": "any"
  }
}

=== floration/mod-creator/examples/azuregrove/spec/advancements/lurker_hunter.json
{
  "$schema": "../../.modcreator/schema/advancement.json",
  "kind": "advancement",
  "id": "lurker_hunter",
  "name": "Lurker Hunter",
  "advancement": {
    "parent": "azure_grove",
    "description": "Defeat a Grove Lurker and a Bluetusk",
    "icon": "azurite_sword",
    "frame": "challenge",
    "criteria": [
      {
        "type": "kill",
        "mob": "grove_lurker"
      },
      {
        "type": "kill",
        "mob": "bluetusk"
      }
    ],
    "rewards": {
      "experience": 50,
      "items": [
        {
          "item": "azurite",
          "count": 4
        },
        {
          "item": "azure_plum",
          "count": 2
        }
      ]
    }
  }
}

=== floration/mod-creator/examples/ruby/spec/advancements/moth_friend.json
{
  "$schema": "../../.modcreator/schema/advancement.json",
  "kind": "advancement",
  "id": "moth_friend",
  "name": "Moth Friend",
  "advancement": {
    "parent": "ruby",
    "description": "Tame a Glowmoth",
    "icon": "glowmoth_spawn_egg",
    "frame": "goal",
    "criteria": [
      {
        "type": "tame",
        "mob": "glowmoth"
      }
    ]
  }
}
